const qnaList = [
  {
    q: "1. 친구와 함께 여행장소를 정하려는 당신은",
  },
  {
    q: "2. 여행 계획을 세우려고 하는데 ",
  },
  {
    q: "3. 여행 날 당일 약속시간에 늦잠을 자버린 친구!, 30분이 늦을것 같다고 하는데,,,",
  },
];

const infoList = [
  {
    id: "enfp",
    name: "대책없이 신나는 탐험가",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "enfj",
    name: "난 핸들이 고장난 8톤 트럭",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "entp",
    name: "이 여행에 주인공은 나야!",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "entj",
    name: "친구들의 급발진 방지턱",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "esfp",
    name: "모두 내말에 집중해!",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "esfj",
    name: "있는거 빼고 다없소",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "estp",
    name: "빵터지는 과자봉지",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "estj",
    name: "네비게이션 목소리의 주인공",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "infp",
    name: "대책없이 끌려가는 뒷바퀴",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "infj",
    name: "자율주행 브레이크",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "intp",
    name: "충전이 필요한 스마트폰",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "intj",
    name: "장거리에 힘든 계기판",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "isfp",
    name: "어리둥절 랜턴",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "isfj",
    name: "비가 오~는~날↗️엔↘️ 나를 찾아와",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "istp",
    name: "너만 있으면 돼,삼각대",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
  {
    id: "istj",
    name: "혼자가는 앞바퀴",
    driven: 3,
    active: 1,
    funny: 5,
    desc: "",
    matched: "enfp",
    unmatched: "isfj",
  },
];
